module.exports = ({ instance: i, headers: h }) => ({
  custom_agent_roles: require("./custom_agent_roles")({ i, h }),
  end_users: require("./end_users")({ i, h }),
  group_memberships: require("./group_memberships")({ i, h }),
  groups: require("./groups")({ i, h }),
  organizations: require("./organizations")({ i, h }),
  organization_fields: require("./organization_fields")({ i, h }),
  organization_memberships: require("./organization_memberships")({ i, h }),
  search: require("./search")({ i, h }),
  suspended_tickets: require("./suspended_tickets")({ i, h }),
  tags: require("./tags")({ i, h }),
  ticket_activities: require("./ticket_activities")({ i, h }),
  ticket_comments: require("./ticket_comments")({ i, h }),
  ticket_fields: require("./ticket_fields")({ i, h }),
  ticket_forms: require("./ticket_forms")({ i, h }),
  ticket_import: require("./ticket_import")({ i, h }),
  ticket_metrics: require("./ticket_metrics")({ i, h }),
  tickets: require("./tickets")({ i, h }),
  user_fields: require("./user_fields")({ i, h }),
  user_passwords: require("./user_passwords")({ i, h }),
  users: require("./users")({ i, h }),
  views: require("./views")({ i, h })
});
